name: Build java package

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push: # Apply to all branches

env:
  CHANGELIST: -SNAPSHOT
  RELEASE_VERSION: 0.0.0

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4

      # Execute shared runner setup
      - uses: ./.github/actions/setup-runner

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew integrationTest -Prevision=${{ env.RELEASE_VERSION }} -Pchangelist=${{ env.CHANGELIST }}
          working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4

      # Execute shared runner setup
      - uses: ./.github/actions/setup-runner

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew test -Prevision=${{ env.RELEASE_VERSION }} -Pchangelist=${{ env.CHANGELIST }}
          working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-check-without-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4

      # Execute shared runner setup
      - uses: ./.github/actions/setup-runner

      - name: Run check
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew check -x test -x integrationTest -Prevision=${{ env.RELEASE_VERSION }} -Pchangelist=${{ env.CHANGELIST }}
          working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-executable:
    runs-on: ubuntu-latest
    needs:
      - run-integration-test
      - run-unit-test
      - run-check-without-test
    permissions:
      contents: write
      packages: read
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4

      # Execute shared runner setup
      - uses: ./.github/actions/setup-runner

      - name: retrieve jre cache
        id: jre-cache
        uses: actions/cache@v4
        with:
          path: sdccc/build/jre
          key: jre-cache

      - name: Build package and download license information
        run: |
          ./gradlew build -x test -x integrationTest -Prevision=${{ env.RELEASE_VERSION }} -Pchangelist=${{ env.CHANGELIST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Fetch results from the other jobs for bundling

      - name: Collect executable artifacts
        run: |
          mkdir sdccc/build/zip
          cp -r sdccc/build/lib sdccc/build/zip/
          cp -r sdccc/build/jre sdccc/build/zip/
          cp -r sdccc/build/reports/dependency-license/downloaded-licenses/ sdccc/build/zip/lib/
          cp -r sdccc/build/reports/dependency-license/index.xml sdccc/build/zip/lib/
          cp -r configuration sdccc/build/zip/
          cp sdccc/build/launch4j/SDCcc-*.exe sdccc/build/zip/
          cp README.md sdccc/build/zip/

      - name: Set zip file name for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ZIP_FILE_NAME=SDCcc-${{ env.RELEASE_VERSION }}${{ env.CHANGELIST }}-executable-win64.zip >> $GITHUB_ENV

      - name: Install zip
        if: startsWith(github.ref, 'refs/tags/')
        uses: montudor/action-zip@v1

      - name: Zip executable
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: sdccc/build/zip
        run: |
          zip -qq -r ${{ env.ZIP_FILE_NAME }} .

      - name: Zip test results
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: sdccc/build/
        run: |
          zip -qq -r test-results.zip reports/tests reports/checkstyle reports/spotbugs reports/detekt

      - name: Attach artifacts to snapshot
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CHANGELOG.md
            sdccc/build/zip/${{ env.ZIP_FILE_NAME }}
            sdccc/build/test-results.zip
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          body_path: CHANGELOG.md
